version: "3.8"

services:
  eureka-server:
    image: ghcr.io/<your-github-username>/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true
