name: CI/CD for Eureka Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK for Maven/Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build Spring Boot JAR
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      # Login to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build & Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/eureka-server:latest .
          docker push ghcr.io/${{ github.repository }}/eureka-server:latest

      # Deploy to VPS
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/eureka-server
            docker compose pull
            docker compose up -d
